image: maven:3.9.9-eclipse-temurin-17-alpine
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  TRIGGER_CACHE: "off"

stages:
  - cache
  - tests

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"


generate_cache:
  stage: cache
  tags:
    - formation
  script:
    - mvn compile
  cache:
    key: m2
    paths:
      - .m2/
    policy: push
  rules:
     - changes:
         - pom.xml
       when: on_success
     - if: $TRIGGER_CACHE == "on"

test:
  stage: tests
  tags:
    - formation
  script:
    - mvn test
    # afficher la couverture totale dans la sortie
    - cat target/site/jacoco/index.html
  # la regex ci après va scruter la sortie de la console du job
  coverage: /Total.*?([0-9]{1,3})%/
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    access: developer
    expire_in: "1 hour"
    reports:
      junit: target/surefire-reports/TEST-*.xml
      coverage_report:
        path: target/site/jacoco/jacoco.xml
        coverage_format: jacoco
  cache:
    key: m2
    policy: pull
    untracked: true
      
