# nom arbitraire
test:
  # association entre le job et un runner qualifié avec cette valeur
  tags:
    - formation
  # image du job
  image: maven:3.9.9-eclipse-temurin-17-alpine
  # liste des commandes a exécuter dans l'ordre
  script:
    - mvn compile
